# Generated by Django 5.2.7 on 2025-11-22 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_nombre', models.CharField(default='Hotel sin nombre', max_length=150, verbose_name='Nombre del hotel')),
                ('hotel_eslogan', models.CharField(blank=True, max_length=200, verbose_name='Eslogan')),
                ('hotel_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto')),
                ('hotel_telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('hotel_direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('moneda', models.CharField(choices=[('COP', 'Peso colombiano (COP)'), ('USD', 'Dólar estadounidense (USD)'), ('EUR', 'Euro (EUR)')], default='COP', max_length=3, verbose_name='Moneda por defecto')),
                ('zona_horaria', models.CharField(default='America/Bogota', max_length=50, verbose_name='Zona horaria')),
                ('hora_checkin', models.TimeField(default=datetime.time(15, 0), verbose_name='Hora estándar de check-in')),
                ('hora_checkout', models.TimeField(default=datetime.time(12, 0), verbose_name='Hora estándar de check-out')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='IVA (%)')),
                ('cargo_servicio_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cargo por servicio (%)')),
                ('permitir_overbooking', models.BooleanField(default=False, help_text='Si está activo, se pueden confirmar reservas aunque la ocupación esté al límite.', verbose_name='Permitir overbooking')),
                ('horas_min_cancelacion_sin_penalidad', models.PositiveIntegerField(default=24, help_text='Horas antes del check-in en las que se puede cancelar sin aplicar penalidades.', verbose_name='Horas mínimas para cancelar sin penalización')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración general',
                'verbose_name_plural': 'Configuración general',
            },
        ),
    ]
