# Generated by Django 5.2.7 on 2025-11-23 03:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0005_alter_payment_amount_alter_payment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ROOM_SERVICE', 'Room service'), ('RESTAURANTE', 'Restaurante y bar'), ('LAVANDERIA', 'Lavandería'), ('SPA', 'Spa y bienestar'), ('TRANSPORTE', 'Transporte'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio unitario base del servicio (COP).', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Si es 0 se usará el precio base del servicio.', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('FACTURADO', 'Facturado / cerrado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True)),
                ('agregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_registrados', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_servicio', to='reservas.reservation')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Consumo de servicio',
                'verbose_name_plural': 'Consumos de servicio',
                'ordering': ['-creado_en'],
            },
        ),
    ]
