# Generated by Django 5.2.7 on 2025-11-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=80)),
                ('tipo', models.CharField(choices=[('SENCILLA', 'Sencilla'), ('DOBLE', 'Doble'), ('SUITE', 'Suite'), ('FAMILIAR', 'Familiar')], default='SENCILLA', max_length=20)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('RESERVADA', 'Reservada'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'Mantenimiento'), ('BLOQUEADA', 'Bloqueada')], db_index=True, default='LIBRE', max_length=20)),
                ('piso', models.PositiveIntegerField(default=1)),
                ('capacidad', models.PositiveIntegerField(default=2)),
                ('camas', models.PositiveIntegerField(default=1)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='habitaciones/')),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['piso', 'codigo'],
            },
        ),
    ]
