# Generated by Django 5.2.7 on 2025-11-17 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_tipohabitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='camas',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='precio_noche',
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='habitaciones.tipohabitacion'),
        ),
    ]
