# Generated by Django 5.2.7 on 2025-10-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pax',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
