# Generated by Django 5.2.7 on 2025-11-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hotel', '0002_reservation_pax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
