# Generated by Django 5.2.7 on 2025-11-22 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual'), ('PERSONALIZADO', 'Personalizado')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(max_length=255, upload_to='reportes/')),
                ('total_reservas', models.IntegerField(default=0)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
