# Generated by Django 5.2.7 on 2025-11-18 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0003_remove_habitacion_camas_remove_habitacion_capacidad_and_more'),
        ('reservas', '0005_alter_payment_amount_alter_payment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huesped_principal', models.CharField(max_length=150)),
                ('fecha_check_in_prevista', models.DateField()),
                ('fecha_check_out_prevista', models.DateField()),
                ('fecha_check_in_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_check_out_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de check-in'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('NO_SHOW', 'No show'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('total_hospedaje', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estadias_creadas', to=settings.AUTH_USER_MODEL)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estadias', to='habitaciones.habitacion', verbose_name='Habitación')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estadia', to='reservas.reservation', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Estadía',
                'verbose_name_plural': 'Estadías',
            },
        ),
    ]
