# Generated by Django 5.2.7 on 2025-11-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadia',
            options={'ordering': ['-fecha_check_in_prevista', 'habitacion__codigo'], 'verbose_name': 'Estadía', 'verbose_name_plural': 'Estadías'},
        ),
        migrations.AlterField(
            model_name='estadia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de check-in'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'Ocupada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='fecha_check_in_prevista',
            field=models.DateField(verbose_name='Check-in previsto'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='fecha_check_in_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in real'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='fecha_check_out_prevista',
            field=models.DateField(verbose_name='Check-out previsto'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='fecha_check_out_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-out real'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='huesped_principal',
            field=models.CharField(max_length=150, verbose_name='Huésped principal'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='total_hospedaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total hospedaje'),
        ),
    ]
