# Generated by Django 5.2.7 on 2025-11-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='client',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='guests',
            new_name='pax_adults',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='nightly_rate',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='nightly_rate',
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pax_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OCCUPIED', 'Ocupada'), ('MAINTENANCE', 'Mantenimiento'), ('BLOCKED', 'Bloqueada')], default='AVAILABLE', max_length=12),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='capacity_adults',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='capacity_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Reservada'), ('CHECKED_IN', 'Check-In'), ('CHECKED_OUT', 'Check-Out'), ('CANCELLED', 'Cancelada')], default='BOOKED', max_length=12),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
