# Generated by Django 5.2.7 on 2025-11-17 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_payment_reservation_delete_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('OTHER', 'Otro')], default='CASH', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Número de comprobante, referencia bancaria, etc.', max_length=50, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='adults',
            field=models.PositiveIntegerField(default=1, verbose_name='Adultos'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(verbose_name='Fecha de check-in'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(verbose_name='Fecha de check-out'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='children',
            field=models.PositiveIntegerField(default=0, verbose_name='Niños'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del huésped'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(max_length=120, verbose_name='Nombre del huésped'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono del huésped'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas internas'),
        ),
    ]
